STRING_SRC = html_deal.c uri_deal.c json_deal.c                                                                     
STRING_OBJ = $(STRING_SRC:%.c=%.o)

ENCODE_SRC = cs_secret.c cs_sns_oi_tea.c cs_oi_tea.c
ENCODE_OBJ = $(ENCODE_SRC:%.c=%.o)
