<?cs #:如果是首屏用的话?>
<?cs if: subcount(feeds.firstpage_data) ?>
	<?cs each:item=feeds.firstpage_data.mergeData ?>
	{
		ver:'<?cs  var:item.ver ?>',
		appid:'<?cs  var:item.appid ?>',
		typeid:'<?cs  var:item.typeid ?>',
		key:'<?cs  var:item.key ?>',
		flag:'<?cs  var:item.flag ?>',
		dataonly:'<?cs var:item.dataonly ?>',
		titleTemp:'<?cs  var:item.titleTemp ?>',
		summaryTemp:'<?cs  var:item.summaryTemp ?>',
		feedno:'<?cs  var:item.feedno ?>',
		title:'<?cs  var:json_encode(item.title, 1) ?>',
		summary:'<?cs  var:json_encode(item.summary, 1) ?>',
		appiconid:'<?cs  var:item.appiconid ?>',
		clscFold:'<?cs  var:item.clscFold ?>',
		abstime:'<?cs  var:item.abstime ?>',
		feedstime:'<?cs  var:item.feedstime ?>',
		userHome:'<?cs  var:item.userHome ?>',
		namecardLink:'<?cs  var:item.namecardLink ?>',
		ouin:'<?cs  var:item.ouin ?>',
		uin:'<?cs  var:item.uin ?>',
		foldFeed:'<?cs  var:item.foldFeed ?>',
		foldFeedTitle:'<?cs  var:item.foldFeedTitle ?>',
		showEbtn:'<?cs  var:item.showEbtn ?>',
		scope:'0',
		hideExtend:'<?cs  var:item.hideExtend ?>',
		nickname:'<?cs  var:json_encode(item.nickname, 1) ?>',
		remark:'<?cs  var:json_encode(item.remark, 1) ?>',
		type:'<?cs  var:item.type ?>',
		vip:'<?cs  var:item.vip ?>',
		info_user_name:'<?cs  var:item.info_user_name ?>',
		logimg:'<?cs  var:item.logimg ?>',
		bor:'<?cs  var:item.bor ?>',
		lastFeedBor:'<?cs  var:item.lastFeedBor ?>',
		list_bor2:'<?cs  var:item.list_bor2 ?>',
		info_user_display:'<?cs  var:item.info_user_display ?>',
		oprType:'<?cs  var:item.oprType ?>',
		otherflag:'<?cs  var:item.otherflag ?>',
		rightflag:'<?cs  var:item.rightflag ?>',
		html:'<?cs  var:json_encode(item.html, 1) ?>'
	},
	<?cs /each ?>
<?cs elif:subcount(feeds.friend_data) ?>
	<?cs each:item=feeds.friend_data.mergeData ?>
	{
		ver:'<?cs  var:item.ver ?>',
		appid:'<?cs  var:item.appid ?>',
		typeid:'<?cs  var:item.typeid ?>',
		key:'<?cs  var:item.key ?>',
		flag:'<?cs  var:item.flag ?>',
		dataonly:'<?cs var:item.dataonly ?>',
		titleTemp:'<?cs  var:item.titleTemp ?>',
		summaryTemp:'<?cs  var:item.summaryTemp ?>',
		feedno:'<?cs  var:item.feedno ?>',
		title:'<?cs  var:json_encode(item.title, 1) ?>',
		summary:'<?cs  var:json_encode(item.summary, 1) ?>',
		appiconid:'<?cs  var:item.appiconid ?>',
		clscFold:'<?cs  var:item.clscFold ?>',
		abstime:'<?cs  var:item.abstime ?>',
		feedstime:'<?cs  var:item.feedstime ?>',
		userHome:'<?cs  var:item.userHome ?>',
		namecardLink:'<?cs  var:item.namecardLink ?>',
		ouin:'<?cs  var:item.ouin ?>',
		uin:'<?cs  var:item.uin ?>',
		foldFeed:'<?cs  var:item.foldFeed ?>',
		foldFeedTitle:'<?cs  var:item.foldFeedTitle ?>',
		showEbtn:'<?cs  var:item.showEbtn ?>',
		scope:'0',
		hideExtend:'<?cs  var:item.hideExtend ?>',
		nickname:'<?cs  var:json_encode(item.nickname, 1) ?>',
		remark:'<?cs  var:json_encode(item.remark, 1) ?>',
		type:'<?cs  var:item.type ?>',
		vip:'<?cs  var:item.vip ?>',
		info_user_name:'<?cs  var:item.info_user_name ?>',
		logimg:'<?cs  var:item.logimg ?>',
		bor:'<?cs  var:item.bor ?>',
		lastFeedBor:'<?cs  var:item.lastFeedBor ?>',
		list_bor2:'<?cs  var:item.list_bor2 ?>',
		info_user_display:'<?cs  var:item.info_user_display ?>',
		oprType:'<?cs  var:item.oprType ?>',
		otherflag:'<?cs  var:item.otherflag ?>',
		rightflag:'<?cs  var:item.rightflag ?>',
		html:'<?cs var:json_encode(item.html, 1) ?>'
	},
	<?cs /each ?>
<?cs /if ?>

