_Callback({
	result:'<?cs  var:feeds.type ?>',
	message:'<?cs  var:feeds.message ?>',
	main:{
		needFold:'<?cs  var:feeds.needFold ?>',
		icServerTime:'<?cs  var:feeds.icServerTime ?>',
		icView:'<?cs  var:feeds.icView ?>',
		daylist:'<?cs  var:feeds.g_daylist ?>',
		uinlist:'<?cs  var:feeds.g_uinlist ?>',
		hasMoreFeeds_0:<?cs  var:feeds.hasMoreFeeds_0 ?>,
		hasMoreFeeds_1:<?cs  var:feeds.hasMoreFeeds_1 ?>,
		hasMoreFeeds_100:true,
		foldAllHostBTNClass:'<?cs  var:feeds.foldAllHostBTNClass ?>',
		foldAllHostBTNTitle:'<?cs  var:feeds.foldAllHostBTNTitle ?>',
		foldAllHostFeedDisplay:'<?cs  var:feeds.foldAllHostFeedDisplay ?>',
		friend_more:'<?cs  var:feeds.friend_more ?>',
		host_more:'<?cs  var:feeds.host_more ?>',
		aboutHostFeeds_new_cnt:'<?cs  var:feeds.aboutHostFeeds_new_cnt ?>',
		replyHostFeeds_new_cnt:'<?cs  var:feeds.replyHostFeeds_new_cnt ?>',
		myFeeds_new_cnt:'<?cs  var:feeds.myFeeds_new_cnt ?>',
		friendFeeds_new_cnt:'<?cs  var:feeds.friendFeeds_new_cnt ?>',
		newfeeds_uinlist:'<?cs  var:feeds.newfeeds_uinlist ?>',
		newfeeds_uinlist_more:'<?cs  var:feeds.newfeeds_uinlist_more ?>',
		newfeeds_special_cnt:'<?cs  var:feeds.newfeeds_special_cnt ?>',
		newfeeds_friend_cnt:'<?cs  var:feeds.newfeeds_friend_cnt ?>',
		newfeeds_follow_cnt:'<?cs  var:feeds.newfeeds_follow_cnt ?>',
		newfeeds_group_cnt:'<?cs  var:feeds.newfeeds_group_cnt ?>',
		tips:'<?cs  var:feeds.tips ?>',
		feedstips:'<?cs  var:feeds.feedstips ?>',
		js_showtips:'<?cs  var:feeds.js_showtips ?>',
		lastaccesstime:'<?cs  var:feeds.lastaccesstime ?>',
		lastAccessRelateTime:'<?cs  var:feeds.lastAccessRelateTime ?>',
		begintime:'<?cs  var:feeds.begintime ?>',
		dayspac:'<?cs var:feeds.dayspac ?>',
		QzoneFeedsKey:'<?cs  var:feeds.QzoneFeedsKey ?>'
	},
	host_data:[
		<?cs each:item = feeds.host_data ?>
		{
			ver:'<?cs  var:item.ver ?>',
			appid:'<?cs  var:item.appid ?>',
			typeid:'<?cs  var:item.typeid ?>',
			key:'<?cs  var:item.key ?>',
			flag:'<?cs  var:item.flag ?>',
			dataonly:'<?cs var:item.dataonly ?>',
			titleTemp:'<?cs  var:item.titleTemp ?>',
			summaryTemp:'<?cs  var:item.summaryTemp ?>',
			feedno:'<?cs  var:item.feedno ?>',
			title:'<?cs  var:item.title ?>',
			summary:'<?cs  var:item.summary ?>',
			appiconid:'<?cs  var:item.appiconid ?>',
			clscFold:'<?cs  var:item.clscFold ?>',
			abstime:'<?cs  var:item.abstime ?>',
			feedstime:'<?cs  var:item.feedstime ?>',
			userHome:'<?cs  var:item.userHome ?>',
			namecardLink:'<?cs  var:item.namecardLink ?>',
			ouin:'<?cs  var:item.ouin ?>',
			uin:'<?cs  var:item.uin ?>',
			foldFeed:'<?cs  var:item.foldFeed ?>',
			foldFeedTitle:'<?cs  var:item.foldFeedTitle ?>',
			showEbtn:'<?cs  var:item.showEbtn ?>',
			scope:'1',
			hideExtend:'<?cs  var:item.hideExtend ?>',
			nickname:'<?cs  var:item.nickname ?>',
			remark:'<?cs  var:item.remark ?>',
			type:'<?cs  var:item.type ?>',
			vip:'<?cs  var:item.vip ?>',
			bitmap:'<?cs  var:item.bitmap ?>',
			yybitmap:'<?cs  var:item.yybitmap ?>',
			info_user_name:'<?cs  var:item.info_user_name ?>',
			logimg:'<?cs  var:item.logimg ?>',
			bor:'<?cs  var:item.bor ?>',
			lastFeedBor:'<?cs  var:item.lastFeedBor ?>',
			list_bor2:'<?cs  var:item.list_bor2 ?>',
			info_user_display:'<?cs  var:item.info_user_display ?>',
			oprType:'<?cs  var:item.oprType ?>',
			otherflag:'<?cs  var:item.otherflag ?>',
			rightflag:'<?cs  var:item.rightflag ?>'
		},
		<?cs /each ?>
		undefined
	],
	about_data:[
			<?cs each:item = feeds.about_data ?>
			{
					ver:'<?cs  var:item.ver ?>',
					appid:'<?cs  var:item.appid ?>',
					typeid:'<?cs  var:item.typeid ?>',
					key:'<?cs  var:item.key ?>',
					flag:'<?cs  var:item.flag ?>',
					dataonly:'<?cs var:item.dataonly ?>',
					titleTemp:'<?cs  var:item.titleTemp ?>',
					summaryTemp:'<?cs  var:item.summaryTemp ?>',
					feedno:'<?cs  var:item.feedno ?>',
					title:'<?cs  var:item.title ?>',
					summary:'<?cs  var:item.summary ?>',
					appiconid:'<?cs  var:item.appiconid ?>',
					clscFold:'<?cs  var:item.clscFold ?>',
					abstime:'<?cs  var:item.abstime ?>',
					feedstime:'<?cs  var:item.feedstime ?>',
					userHome:'<?cs  var:item.userHome ?>',
					namecardLink:'<?cs  var:item.namecardLink ?>',
					ouin:'<?cs  var:item.ouin ?>',
					uin:'<?cs  var:item.uin ?>',
					foldFeed:'<?cs  var:item.foldFeed ?>',
					foldFeedTitle:'<?cs  var:item.foldFeedTitle ?>',
					showEbtn:'<?cs  var:item.showEbtn ?>',
					scope:'100',
					hideExtend:'<?cs  var:item.hideExtend ?>',
					nickname:'<?cs  var:item.nickname ?>',
					remark:'<?cs  var:item.remark ?>',
					type:'<?cs  var:item.type ?>',
					vip:'<?cs  var:item.vip ?>',
					info_user_name:'<?cs  var:item.info_user_name ?>',
					logimg:'<?cs  var:item.logimg ?>',
					bor:'<?cs  var:item.bor ?>',
					lastFeedBor:'<?cs  var:item.lastFeedBor ?>',
					list_bor2:'<?cs  var:item.list_bor2 ?>',
					info_user_display:'<?cs  var:item.info_user_display ?>',
					oprType:'<?cs  var:item.oprType ?>',
					otherflag:'<?cs  var:item.otherflag ?>'
			},
			<?cs /each ?>
			undefined
	],
	friend_data:[
		<?cs each:item = feeds.friend_data ?>
		{
			ver:'<?cs  var:item.ver ?>',
			appid:'<?cs  var:item.appid ?>',
			typeid:'<?cs  var:item.typeid ?>',
			key:'<?cs  var:item.key ?>',
			flag:'<?cs  var:item.flag ?>',
			dataonly:'0',
			feedno:'<?cs  var:item.feedno ?>',
			title:'<?cs  var:item.title ?>',
			summary:'<?cs  var:item.summary ?>',
			appiconid:'<?cs  var:item.appiconid ?>',
			clscFold:'<?cs  var:item.clscFold ?>',
			abstime:'<?cs  var:item.abstime ?>',
			feedstime:'<?cs  var:item.feedstime ?>',
			userHome:'<?cs  var:item.userHome ?>',
			namecardLink:'<?cs  var:item.namecardLink ?>',
			ouin:'<?cs  var:item.ouin ?>',
			uin:'<?cs  var:item.uin ?>',
			foldFeed:'<?cs  var:item.foldFeed ?>',
			foldFeedTitle:'<?cs  var:item.foldFeedTitle ?>',
			showEbtn:'<?cs  var:item.showEbtn ?>',
			scope:'0',
			hideExtend:'<?cs  var:item.hideExtend ?>',
			nickname:'<?cs  var:item.nickname ?>',
			remark:'<?cs  var:item.remark ?>',
			type:'<?cs  var:item.type ?>',
			vip:'<?cs  var:item.vip ?>',
			info_user_name:'<?cs  var:item.info_user_name ?>',
			logimg:'<?cs  var:item.logimg ?>',
			bor:'<?cs  var:item.bor ?>',
			lastFeedBor:'<?cs  var:item.lastFeedBor ?>',
			list_bor2:'<?cs  var:item.list_bor2 ?>',
			info_user_display:'<?cs  var:item.info_user_display ?>',
			upernum:'<?cs  var:item.upernum ?>',
			oprType:'<?cs  var:item.oprType ?>',
			moreflag:'<?cs  var:item.moreflag ?>',
			otherflag:'<?cs  var:item.otherflag ?>',
			sameuser:{<?cs  var:item.sameuser ?>},
			uper_isfriend:[<?cs var:item.uper_isfriend ?>],
			uperlist:[<?cs  var:item.uperlist ?>]
		},
		<?cs /each ?>
		undefined
	],
	firstpage_data:[
			<?cs each:item = feeds.firstpage_data ?>
			{
					ver:'<?cs  var:item.ver ?>',
					appid:'<?cs  var:item.appid ?>',
					typeid:'<?cs  var:item.typeid ?>',
					key:'<?cs  var:item.key ?>',
					flag:'<?cs  var:item.flag ?>',
					dataonly:'0',
					feedno:'<?cs  var:item.feedno ?>',
					title:'<?cs  var:item.title ?>',
					summary:'<?cs  var:item.summary ?>',
					appiconid:'<?cs  var:item.appiconid ?>',
					clscFold:'<?cs  var:item.clscFold ?>',
					abstime:'<?cs  var:item.abstime ?>',
					feedstime:'<?cs  var:item.feedstime ?>',
					userHome:'<?cs  var:item.userHome ?>',
					namecardLink:'<?cs  var:item.namecardLink ?>',
					ouin:'<?cs  var:item.ouin ?>',
					uin:'<?cs  var:item.uin ?>',
					foldFeed:'<?cs  var:item.foldFeed ?>',
					foldFeedTitle:'<?cs  var:item.foldFeedTitle ?>',
					showEbtn:'<?cs  var:item.showEbtn ?>',
					scope:'0',
					hideExtend:'<?cs  var:item.hideExtend ?>',
					nickname:'<?cs  var:item.nickname ?>',
					remark:'<?cs  var:item.remark ?>',
					type:'<?cs  var:item.type ?>',
					vip:'<?cs  var:item.vip ?>',
					info_user_name:'<?cs  var:item.info_user_name ?>',
					logimg:'<?cs  var:item.logimg ?>',
					bor:'<?cs  var:item.bor ?>',
					lastFeedBor:'<?cs  var:item.lastFeedBor ?>',
					list_bor2:'<?cs  var:item.list_bor2 ?>',
					info_user_display:'<?cs  var:item.info_user_display ?>',
					upernum:'<?cs  var:item.upernum ?>',
					oprType:'<?cs  var:item.oprType ?>',
					moreflag:'<?cs  var:item.moreflag ?>',
					otherflag:'<?cs  var:item.otherflag ?>',
					sameuser:{<?cs  var:item.sameuser ?>},
					uper_isfriend:[<?cs var:item.uper_isfriend ?>],
					uperlist:[<?cs  var:item.uperlist ?>]
			},
			<?cs /each ?>
			undefined
	]
});
