{
	result:'<?cs  var:feeds.type ?>',
	message:'<?cs  var:feeds.message ?>',
	main:{
		needFold:'<?cs  var:feeds.needFold ?>',
		icServerTime:'<?cs  var:feeds.icServerTime ?>',
		icView:'<?cs  var:feeds.icView ?>',
		daylist:'<?cs  var:feeds.g_daylist ?>',
		uinlist:'<?cs  var:feeds.g_uinlist ?>',
		hasMoreFeeds_0:<?cs  var:feeds.hasMoreFeeds_0 ?>,
		hasMoreFeeds_1:<?cs  var:feeds.hasMoreFeeds_1 ?>,
		hasMoreFeeds_100:true,
		foldAllHostBTNClass:'<?cs  var:feeds.foldAllHostBTNClass ?>',
		foldAllHostBTNTitle:'<?cs  var:feeds.foldAllHostBTNTitle ?>',
		foldAllHostFeedDisplay:'<?cs  var:feeds.foldAllHostFeedDisplay ?>',
		friend_more:'<?cs  var:feeds.friend_more ?>',
		host_more:'<?cs  var:feeds.host_more ?>',
		aboutHostFeeds_new_cnt:'<?cs  var:feeds.aboutHostFeeds_new_cnt ?>',
		replyHostFeeds_new_cnt:'<?cs  var:feeds.replyHostFeeds_new_cnt ?>',
		host_pav_offset:'<?cs  var:feeds.host_pav_offset ?>',
		get_visitorfeed:'<?cs  var:feeds.get_visitorfeed ?>',
		myFeeds_new_cnt:'<?cs  var:feeds.myFeeds_new_cnt ?>',
		friendFeeds_new_cnt:'<?cs  var:feeds.friendFeeds_new_cnt ?>',
		friendFeeds_newblog_cnt:'<?cs  var:feeds.friendFeeds_newblog_cnt ?>',
		friendFeeds_newphoto_cnt:'<?cs  var:feeds.friendFeeds_newphoto_cnt ?>',
		newfeeds_uinlist:'<?cs  var:feeds.newfeeds_uinlist ?>',
		newfeeds_uinlist_more:'<?cs  var:feeds.newfeeds_uinlist_more ?>',
		newfeeds_special_cnt:'<?cs  var:feeds.newfeeds_special_cnt ?>',
		newfeeds_friend_cnt:'<?cs  var:feeds.newfeeds_friend_cnt ?>',
		newfeeds_follow_cnt:'<?cs  var:feeds.newfeeds_follow_cnt ?>',
		newfeeds_group_cnt:'<?cs  var:feeds.newfeeds_group_cnt ?>',
		tips:'<?cs  var:json_encode(feeds.tips, 1) ?>',
		js_showtips:'<?cs  var:json_encode(feeds.js_showtips, 1) ?>',
		lastaccesstime:'<?cs  var:feeds.lastaccesstime ?>',
		lastAccessRelateTime:'<?cs  var:feeds.lastAccessRelateTime ?>',
		begintime:'<?cs  var:feeds.begintime ?>',
		dayspac:'<?cs var:feeds.dayspac ?>',
		hidedNameList:[<?cs  var:feeds.hidedNameList ?>],
		QzoneFeedsKey:'<?cs  var:feeds.QzoneFeedsKey ?>',
		hsFlag:'<?cs var:feeds.hsFlag ?>',
		aisortTotalCount:'<?cs var:feeds.aisortTotalCount ?>',
		aisortEndTime:'<?cs var:feeds.aisortEndTime ?>',
		aisortKeyList:'<?cs var:feeds.aisortKeyList ?>',
		aisortOffset:'<?cs var:feeds.aisortOffset ?>',
		aisortCount:'<?cs var:feeds.aisortCount ?>',
		aisortLastVisitTime:'<?cs var:feeds.aisortLastVisitTime ?>',
		blacklist:'<?cs var:feeds.blacklist ?>'	
	}
}
